### ISSUE TITLE
Invalid grant type when refreshing token

### ISSUE THREAD

**Issue by pluc** [soundcloud/api#132] opened 2021-09-15 14:57 UTC
I am performing this request:

URL: POST https://api.soundcloud.com/oauth2/token

Parameters:
- grant_type = refresh_token
- client_id = my_client_id
- client_secret = my_client_secret
- refresh_token = code obtained after a "connect" call

Headers:
- Accept: application/json; charset=utf-8
- Authorization OAuth $code (the same code that is mentioned in refresh_token)

That is exactly the flow described in the documentation [here](https://developers.soundcloud.com/docs/api/guide#refreshing-tokens). The error I'm getting is: 401 Unauthorized, invalid_grant.

What does that mean? My grant is refresh_token, why does the API think it's invalid?

With or without the "Authorization" header is the same output.

**Comment by pluc** [comment] 2021-09-15 19:05
In case the flow is connect -> authorization_code -> refresh_token:

URL: POST https://api.soundcloud.com/oauth2/token

Parameters:
- grant_type = authorization_code
- client_id = my_client_id
- client_secret = my_client_secret
- authorization_code = code obtained after a "connect" call (which here is called `oauth_token`)

Headers:
- Accept: application/json; charset=utf-8
- Authorization: OAuth $code (the same code that is mentioned in authorization_code)

I get the same error there, 401 invalid_grant.

**Comment by mgoodfellow** [comment] 2021-09-15 19:09
Hi @pluc 

You shouldn't be sending an Authorization header.

> authorization_code = code obtained after a "connect" call (which here is called oauth_token)

No, this is an authorization_code you got back from the connect flow, and you are exchanging for an `oauth_token` and a `refresh_token`

As documented via your link: https://developers.soundcloud.com/docs/api/guide#authentication

There are no authorization headers.

The authorization header is used with an `oauth_token` only :)

**Comment by mgoodfellow** [comment] 2021-09-15 19:10
Also, the parameters for the authorization code are:

```
$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code=YOUR_CODE"
```

It is `code` not `authorization_code`

**Comment by pluc** [comment] 2021-09-15 19:26
Thanks @mgoodfellow.

May I suggest that in that case, the error messages should be reflective of what is actually going on? It has nothing to do with the grant_type, which makes it difficult to debug or even know what's going on.

It's also unclear on your API Explorer platform what method needs the Authentication header and which doesn't, given that it's set at the top and the only way to see it is to "Try it Out" and look at the generated curl line.

Updating the "authorization_code" parameter to "code" yields the same response:

URL: POST https://api.soundcloud.com/oauth2/token'

Parameters:
- grant_type = authorization_code
- client_id = my_client_id
- client_secret = my_client_secret
- code: oauth_token code obtained from the connect flow

Headers:
- 'Accept: application/json; charset=utf-8'
- 'Content-Type: application/x-www-form-urlencoded'

Is the "connect flow" code you get back different from the "connect" API method? So my auth should be to go through the connect flow, use that token to call connect, use that token to call authentication_code, and finally use that token to call refresh_token?

**Comment by mgoodfellow** [comment] 2021-09-15 20:05
> May I suggest that in that case, the error messages should be reflective of what is actually going on? It has nothing to do with the grant_type, which makes it difficult to debug or even know what's going on.

I'm going to hazard a guess and say that it's actually saying `invalid_grant` - meaning your authorization doesn't have the required grants to do what it is trying to do - i.e. it is a generic "you don't have access" error. In this case your Authorization header is taking precedence over the rest of the payload, and that Authorization header is invalid, and the call fails.

 > It's also unclear on your API Explorer platform what method needs the Authorization header and which doesn't, given that it's set at the top and the only way to see it is to "Try it Out" and look at the generated curl line.

I'm guessing this is a limitation in how swagger generates it's docs automatically (I think it's swagger?) - but I can see that being a tad confusing in this case. 

> Updating the "authorization_code" parameter to "code" yields the same response:

You still aren't sending all the parameters (assuming that is all the params you are sending in the example you gave) - review the curl command again:

```
$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code=YOUR_CODE"
```

You are missing the `redirect_uri`

The flow is:

* Send user to the connect login page: `https://api.soundcloud.com/connect?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code` - do this in a browser to test
* That page will redirect back to your `redirect_url` page with a `code` parameter in the URL - this is an `authorization_code` you are going to use to generate the `oauth_token` / `refresh_token` pair - extract this and pass it into `code` param below
* Make the curl command as above:

```
$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code=YOUR_CODE"
```

* You will get back a JSON payload with `oauth_token`, `expires_in` and `refresh_token`

* When calling API, use that `oauth_token` in the header for API calls:

```
$ curl "https://api.soundcloud.com/me" \
       -H "accept: application/json; charset=utf-8" \
       -H "Authorization: OAuth ACCESS_TOKEN"
```

* Some time in the future, your `oauth_token` will be expiring - if it expires then when you use it you will get a 401 response (with an `invalid_grant` payload(!!))
* Go through the refresh process - A word of warning - `refresh_tokens` are single use - when you use it you will get a new `oauth_token`, `expires_in` AND `refresh_token` - the `refresh_token` you just used is burnt and can never be used again:

```
$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=refresh_token" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "refresh_token=YOUR_TOKEN" \
```

Note that `redirect_uri` is not needed in this request.

I highly recommend actually trying this process on the command line and using the `curl` commands directly so you can sanity check it all. Once you have done that, move on to implementing a proprietary solution.

**Comment by pluc** [comment] 2021-09-15 21:28
@mgoodfellow I indeed have the "redirect_uri" properly in the code I just didn't copy it here, since it feels largely irrelevant in a method that is completely not involved with the redirect_uri.

So I am doing what you say:
1. User clicks a button and is then sent to the connect flow thing that asks the user to authorize the app
2. I get back an "oauth_token"
3. I then take this token and pass it into the authorization_code call

and at that point we're back to where we were, and I'm getting a 401. So the issue again is that I cannot take the token I obtain from the connect flow to the authorization_code method

**Comment by mgoodfellow** [comment] 2021-09-15 21:38
> since it feels largely irrelevant in a method that is completely not involved with the redirect_uri.

Sorry, are you sending the redirect_uri in the curl example exactly as shown? It isn't irrelevant. The method is very much involved with the redirect_uri - it is a required parameter. 

> I get back an "oauth_token"

No, you get back an authorization_code - you must exchange this for an oauth_token. 

Looks like I can't help you any further I'm afraid and you will need get someone at SoundCloud to help you out.

Just to be 100% sure - you used that exact curl command (I.e. grant_type = authorization_code), using curl, on the command line, with all the same parameters, just with your own values put in? And it doesn't work? That's very strange.

**Comment by pluc** [comment] 2021-09-15 21:45
Yes.

> curl -X POST "https://api.soundcloud.com/oauth2/token" -H "accept: application/json; charset=utf-8" -H "Content-Type: application/x-www-form-urlencoded" --data-urlencode "grant_type=authorization_code" --data-urlencode "client_id=blabla" --data-urlencode "client_secret=blabla" --data-urlencode "redirect_uri=blabla" --data-urlencode "code=blabla"
{"code":401,"message":"invalid_grant","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[{"error_message":"invalid_grant"}],"error":null,"error_code":"invalid_grant"}

as for the redirect_url, it might be a required parameters but it doesn't do anything, it doesn't send the user to the redirect url, doesn't call back or anything like what it does where it is actually useful (the connect flow). Maybe it's just to check the integrity of a third parameter for some reason.

**Comment by mgoodfellow** [comment] 2021-09-15 22:02
The only last thing that pops to mind is to make sure that redirect_uri is exactly as it shows under "your apps" - so any trailing slashes, query bits you might have added, and also same protocol (http/https) 

To be sure, make sure to copy and paste it from that field.

Last thing that also springs to mind - an authorization_code can only be used once. If the page you are calling back to already exists and has code running that consumes that authorization_code then you won't be able to use it afterwards.

**Comment by pluc** [comment] 2021-09-15 22:04
The redirect_uri is the same. I have never been able to successfully call authorization_code so that should take care of that problem. Thanks though

**Comment by dasha-kobzeva** [comment] 2021-09-16 08:41
@pluc could you please share your client_id with me so I can see what's going on?

Thank you

**Comment by dasha-kobzeva** [comment] 2021-09-16 08:53
Also one remark regarding our API Explorer:

> It's also unclear on your API Explorer platform what method needs the Authorization header and which doesn't, given that it's set at the top and the only way to see it is to "Try it Out" and look at the generated curl line.

If you look closely, every method that requires authorization is marked with a lock. So you can provide the token to only those methods you are trying out.

<img width="1421" alt="Screenshot 2021-09-16 at 10 50 11" src="https://user-images.githubusercontent.com/56645782/133582022-a72f3e0c-c145-4a23-b588-7e00d7b9eb7b.png">

As shown here `/oauth2/token` has no lock and requires no Auth header.

**Comment by pluc** [comment] 2021-09-16 12:00
That client_id is `bfcc5ba285ffb9959af1f155c7d89cab` @dasha-kobzeva

**Comment by dasha-kobzeva** [comment] 2021-09-16 12:19
Thank you!
Ok, so here are the actions to make for it to work:
1. Call /connect endpoint

URL: `https://secure.soundcloud.com/connect?response_type=code&client_id=bfcc5ba285ffb9959af1f155c7d89cab&redirect_uri=YOUR_REDIRECT`

Redirect_uri has to match the one you registered your app with!

You get to a screen like this one (pic attached) and press `Connect`.
<img width="1421" alt="Screenshot 2021-09-16 at 14 05 10" src="https://user-images.githubusercontent.com/56645782/133610094-325c38ff-c302-4037-b568-7225f5897e42.png">

2. After pressing `Connect` you are being redirected to that redirect_uri you have provided + a code.
You can see it in the attached pic below, in URL bar.
<img width="1403" alt="Screenshot 2021-09-16 at 14 16 09" src="https://user-images.githubusercontent.com/56645782/133610499-4604cca9-c99f-4435-a247-d246e6d39539.png">

3. Extract that code and call `/oauth2/token` endpoint
URL: 
```
curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H "X-Real-Ip: YR_IP_ADDRESS"  \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     -H 'Accept: application/json' \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YR_CLIENT_ID" \
     --data-urlencode "client_secret=YR_SECRET" \
     --data-urlencode "redirect_uri=YR_REDIRECT" \
     --data-urlencode "code=THAT CODE FROM STEP 2"
```
4. You get a token back.


Please try the following steps and let me know if u still see an error.

**Comment by pluc** [comment] 2021-09-16 12:26
Yes, that is what I am doing as you can read in my previous replies. However I am not using cURL and I am not passing X-Real-Ip header, those are the only differences. What I am getting back from copy/pasting your request is, again:

`{"code":401,"message":"invalid_grant","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[{"error_message":"invalid_grant"}],"error":null,"error_code":"invalid_grant"}`

**Comment by dasha-kobzeva** [comment] 2021-09-16 12:27
I just did the flow and I get a response. What are you using instead of curl?

**Comment by pluc** [comment] 2021-09-16 12:29
Right now I used curl to paste your command. I am using the JS SDK to trigger the connect flow, I then pass the obtained token to another script.

**Comment by dasha-kobzeva** [comment] 2021-09-16 12:31
JS SDK is not working, could you please not use it and call /connect differently?

**Comment by dasha-kobzeva** [comment] 2021-09-16 12:31
JS SDK is passing the actual token back, not the auth code. But its deprecated and wont work shortly

**Comment by pluc** [comment] 2021-09-16 12:33
heh, well that explains it.

maybe you should take it out of your entire documentation

**Comment by mgoodfellow** [comment] 2021-09-16 12:34
> Send user to the connect login page: https://api.soundcloud.com/connect?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code - do this in a browser to test

So when I gave you specific detailed instructions last night you didn't follow them? 

It's like blood from a stone, I spent a fair while trying to help you reproduce this step by step. It's a touch maddening that you didn't do what I said then complained some different process you did yourself didn't work.

**Comment by mgoodfellow** [comment] 2021-09-16 12:38
Complete and utter waste of my time, then you just use this whole thread as an excuse to just complain about some documentation _yet again_

I literally documented everything, every command, in order, to test this whole process in great detail and you didn't follow my instructions.

I won't get back that time, I definitely won't engage with you in future. How many times did I specifically check and ask you were doing what I outlined in meticulous detail?? Ridiculous.

**Comment by pluc** [comment] 2021-09-16 12:42
@mgoodfellow What you instructed me to do is what the SDK already does, I didn't see a point to do it "more manually" than how I was already manually doing it since I was getting that URL regardless (which I validated) - now they are saying that their SDK shouldn't be used so if you want to blame someone for wasting your time I suggest you look elsewhere

**Comment by dasha-kobzeva** [comment] 2021-09-16 12:44
@mgoodfellow thank you for supporting me on the matter! :)

@pluc we have made notes that the JS SDK was deprecated multiple times, in multiple places.
https://github.com/soundcloud/api#i-have-a-questions-about-the-sdks-can-i-post-them-here
https://github.com/soundcloud/soundcloud-javascript#%EF%B8%8F%EF%B8%8Fdeprecated---no-longer-maintained%EF%B8%8F%EF%B8%8F

We will update the documentation when we have the capacity.

You imagine this huge force of developers, but frankly, we are not that many, and currently, API is being supported by 1 person. So please forgive us for not being up-to-date, we are trying our best.
 
I'm closing this thread, as there is no other way we can provide you help than the instructions above!

**Comment by mgoodfellow** [comment] 2021-09-16 12:45
You are a time waster.

Have you never worked with software before? Why make such ridiculous assumptions? 

Break the problem down to its most basic state and try to reproduce if you want to try to pinpoint an error or mistake.

Instead you have wasted everyone's time by pretending you were doing what we asked you to do.

You have made a simple problem infinitely harder to debug. 

It's on you.

**Closed by dasha-kobzeva** 2021-09-16 12:44 UTC

**Comment by pluc** [comment] 2021-09-16 12:50
Why assume that the SDK they are hosting and have documentation for works? Gee, I don't know? Maybe because they're hosting it and they have documentation for it?

You're going about problem-solving the wrong way. You're trying to find root causes  when there are layers of shit provided by SoundCloud that shouldn't be there and worst than not working, they just work in *different ways*. I don't care about root causes, I care about what's wrong with my implementation. And then you want to blame users for trying to navigate this shitshow? C'mon.

**Comment by mgoodfellow** [comment] 2021-09-16 12:59
> Why assume that the SDK they are hosting and have documentation for works? Gee, I don't know? Maybe because they're hosting it and they have documentation for it?

But that's not what we were talking about in this issue - in fact _you didn't even mention it once in this entire thread!_

So you led us down the garden path from the get go.

> You're going about problem-solving the wrong way. 

I'm really not, break the problem down into simple steps. Once it's working, find out why the more complex solution wasn't working. Look for differences.

> You're trying to find root causes 

You are literally the root cause of this issue 😂

> I don't care about root causes, I care about what's wrong with my implementation.

Other than being one of the stupidest statements I've read today, what you were doing via the SDK is totally different to what we were doing here - for one, it doesn't know your client_secret. That's one glaring difference from the start. So learning the root cause would have shown you exactly what was wrong with your implementation.

Anyway no point arguing with someone who doesn't understand how to work through a problem in simple baby steps. Literally gave you copy and paste steps. By the way, copy is ctrl-c and paste is ctrl-v on PC.

Anyway, when all is said and done I think you did this entire time wasting show just to have _yet another dig_ at the SoundCloud API.
